---
- name: create users and groups
  hosts: localhost
  become: yes
  tasks:
    - name: create users
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - galina
        - tim
        - ann