- hosts: all
  become: yes
  tasks:
  - name: Install apache httpd (state=present is optional)
    ansible.builtin.apt:
      name: [apache2, tree]
      state: present
      update_cache: yes
    register: hello