- hosts: all
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ./kaizen # local mashine
      dest: /tmp    # remote mashine
      remote_src: yes

  - name: create file
    ansible.builtin.shell: touch hello